language:
  elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.2.6
    - otp_release: 20.1
      elixir: 1.6.1

services:
  - redis-server

script:
  - if [[ `elixir -v` = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test --trace
